/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JOptionPane;
import modelo.categoriaModelo;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import util.HibernateUtil;

/**
 *
 * @author David
 */
public class cadastroCategoria extends javax.swing.JFrame {
    
    private categoriaModelo categoria;
    private Boolean editando;

    public categoriaModelo getCategoria() {
        return categoria;
    }

    public void setCategoria(categoriaModelo categoria) {
        this.categoria = categoria;
    }

    public Boolean getEditando() {
        return editando;
    }

    public void setEditando(Boolean editando) {
        this.editando = editando;
    }
    
    public  void remover(){
        SessionFactory SF= HibernateUtil.getSessionFactory();
        Session s = SF.openSession();
        Transaction tx=s.beginTransaction();
        try {
            s.delete(this.categoria);
            tx.commit();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Erro"+e.getMessage());
            tx.rollback();
        }
        s.close();
}
    
    public void salvar(){
         SessionFactory SF= HibernateUtil.getSessionFactory();
        Session s = SF.openSession();
        Transaction tx=s.beginTransaction();
        
        if(this.editando){
   try {
            s.merge(this.categoria);
            tx.commit();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Erro"+e.getMessage());
            tx.rollback();
        }
        
        }
        else{
          try {
            s.save(this.categoria);
            tx.commit();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Erro"+e.getMessage());
            tx.rollback();
        }
        }
        s.close();
    
    }
    

    /**
     * Creates new form cadastroCategoria
     */
    public cadastroCategoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomejLabel1 = new javax.swing.JLabel();
        codigojLabel1 = new javax.swing.JLabel();
        codigojTextField1 = new javax.swing.JTextField();
        nomejTextField1 = new javax.swing.JTextField();
        voltarjButton1 = new javax.swing.JButton();
        gravarjButton2 = new javax.swing.JButton();
        excluirjButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        nomejLabel1.setText("Nome");
        getContentPane().add(nomejLabel1);
        nomejLabel1.setBounds(20, 100, 60, 17);

        codigojLabel1.setText("Codigo");
        getContentPane().add(codigojLabel1);
        codigojLabel1.setBounds(20, 60, 49, 17);

        codigojTextField1.setEditable(false);
        codigojTextField1.setFocusable(false);
        getContentPane().add(codigojTextField1);
        codigojTextField1.setBounds(100, 50, 70, 30);
        getContentPane().add(nomejTextField1);
        nomejTextField1.setBounds(100, 100, 220, 30);

        voltarjButton1.setText("Voltar");
        getContentPane().add(voltarjButton1);
        voltarjButton1.setBounds(290, 180, 130, 40);

        gravarjButton2.setText("Gravar");
        gravarjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gravarjButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(gravarjButton2);
        gravarjButton2.setBounds(10, 180, 130, 40);

        excluirjButton3.setText("Excluir");
        getContentPane().add(excluirjButton3);
        excluirjButton3.setBounds(150, 180, 130, 40);

        setSize(new java.awt.Dimension(446, 277));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gravarjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gravarjButton2ActionPerformed
      if(nomejTextField1.getText().compareTo("")==0){
      JOptionPane.showMessageDialog(null,"O campo nao deve ser vazio!");}
      else{this.salvar();}  
    }//GEN-LAST:event_gravarjButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codigojLabel1;
    private javax.swing.JTextField codigojTextField1;
    private javax.swing.JButton excluirjButton3;
    private javax.swing.JButton gravarjButton2;
    private javax.swing.JLabel nomejLabel1;
    private javax.swing.JTextField nomejTextField1;
    private javax.swing.JButton voltarjButton1;
    // End of variables declaration//GEN-END:variables
}
